#!/usr/bin/env python3
"""Print the runtime diff report generated by js_page_runtime_parity_runner."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-id", required=True)
    args = parser.parse_args()
    path = ROOT / "public-range-evidence" / "raw" / "realistic-captcha-risk-lab" / args.run_id / "runtime-diff-report.json"
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    print(json.dumps({"status": "PASS", "diff_report_path": str(path), "diff": data}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

